name: maps
channels:
  - conda-forge
dependencies:
  - python=3.6
  - basemap
  - basemap-data-hires
  - bokeh
  - cartopy
  - folium
  - geopandas
  - gpxpy
  - jupyter
  - mplleaflet
  - oceans
  - seawater
